DELIMITER //

CREATE FUNCTION hello ()
RETURNS TEXT NO SQL
BEGIN
	DECLARE cur_time TIME DEFAULT CURRENT_TIME;
	CASE 
		WHEN cur_time BETWEEN TIME('6:00') AND TIME('12:00') THEN RETURN 'Доброе утро';
		WHEN cur_time BETWEEN TIME('12:00') AND TIME('18:00') THEN RETURN 'Добрый день';
		WHEN cur_time BETWEEN TIME('18:00') AND TIME('00:00') THEN RETURN 'Добрый вечер';
		WHEN cur_time BETWEEN TIME('00:00') AND TIME('06:00') THEN RETURN 'Доброй ночи';
	END CASE;
END//


